### ISSUE TITLE
translation

### ISSUE THREAD

**Issue by Rello** [Rello/sharereview#1]
https://github.com/nextcloud/docker-ci/issues/647

**Comment by nickvergessen** [comment]
Might want to translate things like https://github.com/Rello/sharereview/blob/main/js/app.js#L47
And not sure excluding appinfo is valid https://github.com/Rello/sharereview/blob/main/.l10nignore#L3

info.xml is always checked for name, summary, description, etc.

**Comment by Rello** [comment]
> Might want to translate things like https://github.com/Rello/sharereview/blob/main/js/app.js#L47 And not sure excluding appinfo is valid https://github.com/Rello/sharereview/blob/main/.l10nignore#L3
> 
> info.xml is always checked for name, summary, description, etc.

thank you. first one is fixed. still fine-tuning.
second one is the same also for my other app, thats why I took over
