### ISSUE TITLE
Berechtigung Fehler/Authorization error

### ISSUE THREAD

**Issue by Schubi2024** [Rello/sharereview#11]
Hallo,

leider habe ich das gleich Problem wie Anfangs mit der vorherigen Version.

" Die App muss im App-Store auf mindestens eine bestimmte Benutzergruppe beschränkt sein. Dadurch wird verhindert, dass die freigegebenen Inhalte versehentlich allen Konten zugänglich gemacht werden."

NC: 30

Gruß
Thomas

..........................................

Hello,

unfortunately I have the same problem as I had with the previous version.

“ The app must be restricted to at least one specific user group in the app store. This prevents the shared content from accidentally being made available to all accounts.”

NC: 30

Greetings
Thomas

**Comment by Rello** [comment]
Hi,
there is an error in the nextcloud logs. can you send this one?

**Comment by Schubi2024** [comment]
Entschuldige. Es hat sich erledigt.
Ich hatte mal Talk installiert und wieder gelöscht.

Im Log stand jetzt fogendes:

QueryException
Could not resolve OCA\Talk\Manager! Class "OCA\Talk\Manager" does not exist

Nach der erneuten Installation von Talk läuft es wieder.

Gruß Thomas

.........................................................

Sorry. It's done now.
I had installed Talk once and deleted it again.

The log now shows the following:

QueryException
Could not resolve OCA\Talk\Manager! Class “OCA\Talk\Manager” does not exist

After reinstalling Talk it works again.

Greetings Thomas

**Comment by Rello** [comment]
oh, wait. das ist aber ein guter Hinweis. das muss ich trotzdem abfangen.
Das Problem kommt daher, dass es Talk Shares gibt, die aber nicht gelöscht wurden durch die Entfernung von Talk

**Comment by Schubi2024** [comment]
Nach der Installation von Talk wurden mir auch Freigeben von Talk angezeigt.
Dann konnte ich diese löschen.
---------------------
 After installing Talk, I was also shown shares of Talk.
I was then able to delete them.

**Comment by ywtoly** [comment]
from QueryException cause
Could not resolve OCA\Talk\Manager! Class "OCA\Talk\Manager" does not exist
----
I recently upgraded to the latest version and encountered the same issue.

**Comment by ywtoly** [comment]
> ## from QueryException cause
> Could not resolve OCA\Talk\Manager! Class "OCA\Talk\Manager" does not exist
> I recently upgraded to the latest version and encountered the same issue.

I haven't installed the Talk app yet

**Comment by Rello** [comment]
> > ## from QueryException cause
> > Could not resolve OCA\Talk\Manager! Class "OCA\Talk\Manager" does not exist
> > I recently upgraded to the latest version and encountered the same issue.
> 
> I haven't installed the Talk app yet

Hello,
yes, thats the issue. I forgot a safety net here for this dependency injection.
the fix is already in testing

**Comment by Rello** [comment]
Hello,
1.3.2 was just released. please let me know

**Comment by ywtoly** [comment]
> Hello, 1.3.2 was just released. please let me know

Updated and currently functioning normally.
 (Talk App not installed)
