### ISSUE TITLE
Error when open App 

### ISSUE THREAD

**Issue by mellow2012** [Rello/sharereview#3]
Server 29.0.3
User Local and LDAP
App 1.0.1
I have assigned a group to the app.
but it still says that one has to be assigned
and I have this error in the log:
`Call to a member function getPath() on null in file '/var/www/vhosts/example.cloud/httpdocs/nextcloud/apps/sharereview/lib/Service/ShareService.php' line 96`

**Comment by Rello** [comment]
Hello,
thank you for reporting this. I will have a look. I think I have an idea already...

**Comment by Rello** [comment]
@mellow2012 update was released. please let me know...

**Comment by mellow2012** [comment]
👍 now i can use it
thank you

**Comment by olive-spore-734** [comment]
Since 1.1.0 i get a similar error:
`Class "OCA\ShareReview\Helper\Exception" not found in file '/var/www/cloud name here/apps/sharereview/lib/Helper/UserHelper.php' line 46`

**Comment by Rello** [comment]
@olive-spore-734 i will check. thank you

**Comment by Enh4rd** [comment]
Since 1.3.3 i get a similar error:
```
Exception array_merge(): Argument #1 must be of type array, null given in file '/var/www/nextcloud/apps/sharereview/lib/Service/ShareService.php' line 92
Undefined variable $formated at /var/www/nextcloud/apps/sharereview/lib/Service/ShareService.php#258
```

The error occurs if there is no shared files.
