### ISSUE TITLE
stop table refresh on demand

### ISSUE THREAD

**Issue by olive-spore-734** [Rello/sharereview#4]
First of all - **thank you** for this, Nextcloud needs it.

Ideas:
- Dont refresh the List or let users decide to pause it. The way it is now i can delete one to three shares until it refreshes and i have to search again. (Asuming this is not a bug)
- Selection of multible shares for deletion
- The UI is quite wide right now, could you maybe add an option to show/hide certain categories, like Permissions, Owner... ?

Thanks again!

**Comment by Rello** [comment]
Hello,
yes. version one. 
open to any suggestions!

- refresh: it should refresh after every action. perhaps your list is long and the refresh "seems" delayed?
- multiple deletions: good point
- columns. yes. e.g. owner/initiator. one is enough

**Comment by Rello** [comment]
fyi
a minor update was released. one column was removed and the username (and not id) is displayed now...

**Comment by Rello** [comment]
thank you for your feedback. a checkbox was added for multi-deletions...


![Bildschirmfoto 2024-09-22 um 18 13 57](https://github.com/user-attachments/assets/7d72e82e-3db1-4a98-901f-ac4ad14bd4c8)
